from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

def create_element(name):
    return OxmlElement(name)

def create_attribute(element, name, value):
    element.set(qn(name), value)

def add_page_number(run):
    fldChar1 = create_element('w:fldChar')
    create_attribute(fldChar1, 'w:fldCharType', 'begin')

    instrText = create_element('w:instrText')
    create_attribute(instrText, 'xml:space', 'preserve')
    instrText.text = "PAGE"

    fldChar2 = create_element('w:fldChar')
    create_attribute(fldChar2, 'w:fldCharType', 'end')

    run._r.append(fldChar1)
    run._r.append(instrText)
    run._r.append(fldChar2)

# 1. INISIALISASI DOKUMEN
doc = Document()

# 2. SETTING STYLE (FONT & WARNA)
style = doc.styles['Normal']
font = style.font
font.name = 'Arial'
font.size = Pt(11)

# Style Heading 1 (BAB)
h1 = doc.styles['Heading 1']
h1.font.name = 'Arial'
h1.font.size = Pt(16)
h1.font.bold = True
h1.font.color.rgb = RGBColor(0, 51, 102) # Dark Blue Corporate

# Style Heading 2 (SUB-BAB)
h2 = doc.styles['Heading 2']
h2.font.name = 'Arial'
h2.font.size = Pt(13)
h2.font.bold = True
h2.font.color.rgb = RGBColor(44, 62, 80) # Dark Gray

# Style Title
title_style = doc.styles['Title']
title_style.font.name = 'Arial'
title_style.font.size = Pt(26)
title_style.font.bold = True
title_style.font.color.rgb = RGBColor(0, 51, 102)

# 3. HEADER & FOOTER
header = doc.sections[0].header
htable = header.add_table(1, 2, width=Inches(6))
htable.autofit = False
htable.columns[0].width = Inches(4.5)
htable.columns[1].width = Inches(1.5)

# Kiri: Info Perusahaan
h_cell = htable.cell(0, 0)
h_p = h_cell.paragraphs[0]
h_run = h_p.add_run("SMART ENGINEX CONSULTANT")
h_run.bold = True
h_run.font.size = Pt(14)
h_run.font.color.rgb = RGBColor(0, 51, 102)
h_p.add_run("\nIntegrated Engineering Solution System").font.size = Pt(9)

# Kanan: Placeholder Logo (Text dulu)
h_cell2 = htable.cell(0, 1)
h_p2 = h_cell2.paragraphs[0]
h_p2.alignment = WD_ALIGN_PARAGRAPH.RIGHT
h_run2 = h_p2.add_run("[LOGO]")
h_run2.font.color.rgb = RGBColor(200, 200, 200)

# Footer (Halaman)
footer = doc.sections[0].footer
f_p = footer.paragraphs[0]
f_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
f_run = f_p.add_run("Generated by SmartENGINEX AI | Hal: ")
f_run.font.size = Pt(8)
f_run.font.color.rgb = RGBColor(128, 128, 128)
add_page_number(f_run)

# 4. HALAMAN JUDUL (COVER)
for i in range(5): doc.add_paragraph() # Spacer
p_title = doc.add_paragraph("LAPORAN PERHITUNGAN TEKNIS\n& ESTIMASI BIAYA", style='Title')
p_title.alignment = WD_ALIGN_PARAGRAPH.CENTER

doc.add_paragraph()
p_sub = doc.add_paragraph("PROYEK: {{NAMA_PROYEK}}")
p_sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
p_sub.style.font.size = Pt(16)
p_sub.style.font.bold = True

p_loc = doc.add_paragraph("LOKASI: {{LOKASI_PROYEK}}")
p_loc.alignment = WD_ALIGN_PARAGRAPH.CENTER

doc.add_paragraph()
p_date = doc.add_paragraph("Tanggal: {{TANGGAL}}")
p_date.alignment = WD_ALIGN_PARAGRAPH.CENTER

doc.add_page_break()

# 5. ISI LAPORAN (TEMPLATE CONTENT)

# BAB I
doc.add_heading('I. DATA PERENCANAAN', level=1)
doc.add_paragraph("Berikut adalah parameter desain yang digunakan dalam analisis ini:")

# Tabel Parameter
table = doc.add_table(rows=1, cols=2)
table.style = 'Table Grid'
hdr_cells = table.rows[0].cells
hdr_cells[0].text = 'Parameter'
hdr_cells[1].text = 'Nilai / Spesifikasi'
# Isi dummy placeholder
data_teknis = [
    ('Standar Beton', 'SNI 2847:2019'),
    ('Standar Gempa', 'SNI 1726:2019'),
    ('Mutu Beton (fc\')', '{{FC_BETON}} MPa'),
    ('Mutu Baja (fy)', '{{FY_BAJA}} MPa'),
    ('Fungsi Bangunan', '{{FUNGSI_BANGUNAN}}')
]
for item, val in data_teknis:
    row_cells = table.add_row().cells
    row_cells[0].text = item
    row_cells[1].text = val

doc.add_paragraph()

# BAB II
doc.add_heading('II. HASIL ANALISIS STRUKTUR', level=1)
doc.add_heading('2.1. Analisis Elemen Balok & Kolom', level=2)
doc.add_paragraph("{{HASIL_ANALISIS_STRUKTUR}}")
doc.add_paragraph("Note: Perhitungan detail terlampir pada lampiran notasi perhitungan.")

doc.add_heading('2.2. Pengecekan Keamanan (Safety Factor)', level=2)
doc.add_paragraph("Berdasarkan hasil analisis, rasio kapasitas penampang adalah sebagai berikut:")
# Placeholder Tabel Safety
table_sf = doc.add_table(rows=1, cols=3)
table_sf.style = 'Light Shading Accent 1'
sf_hdr = table_sf.rows[0].cells
sf_hdr[0].text = 'Elemen'
sf_hdr[1].text = 'Rasio (Mu/Phi Mn)'
sf_hdr[2].text = 'Status'
# Row dummy
row = table_sf.add_row().cells
row[0].text = 'Balok Induk B1'
row[1].text = '{{RATIO_B1}}'
row[2].text = '{{STATUS_B1}}'

doc.add_paragraph()

# BAB III
doc.add_heading('III. ESTIMASI BIAYA (RAB)', level=1)
doc.add_paragraph("Berikut adalah rekapitulasi estimasi biaya konstruksi (Engineering Estimate):")

# Tabel RAB Simple
table_rab = doc.add_table(rows=1, cols=4)
table_rab.style = 'Table Grid'
rab_hdr = table_rab.rows[0].cells
rab_hdr[0].text = 'Uraian Pekerjaan'
rab_hdr[1].text = 'Volume'
rab_hdr[2].text = 'Harga Satuan'
rab_hdr[3].text = 'Total Harga'

# Placeholder Rows RAB
items = [
    ('Pekerjaan Persiapan', '1.0 Ls', 'Rp ...', 'Rp ...'),
    ('Pek. Tanah & Pondasi', '{{VOL_TANAH}} m3', 'Rp ...', 'Rp ...'),
    ('Pek. Beton Struktur', '{{VOL_BETON}} m3', 'Rp ...', 'Rp {{TOTAL_BETON}}'),
    ('Pek. Besi & Bekisting', '{{BERAT_BESI}} kg', 'Rp ...', 'Rp ...'),
]
for uraian, vol, sat, tot in items:
    cells = table_rab.add_row().cells
    cells[0].text = uraian
    cells[1].text = vol
    cells[2].text = sat
    cells[3].text = tot

grand_total = table_rab.add_row().cells
grand_total[0].text = "ESTIMASI TOTAL"
grand_total[3].text = "Rp {{GRAND_TOTAL}}"
grand_total[0].merge(grand_total[2]) # Merge cell

doc.add_paragraph()
doc.add_paragraph("*Harga belum termasuk PPN 11% dan biaya tak terduga (contingency).", style='Quote')

# BAB IV
doc.add_heading('IV. KESIMPULAN & REKOMENDASI', level=1)
doc.add_paragraph("{{KESIMPULAN_AI}}")

# Tanda Tangan
doc.add_paragraph("\n\n")
sig_table = doc.add_table(rows=1, cols=2)
sig_table.width = Inches(6)
sig_table.rows[0].cells[0].text = f"Disiapkan oleh,\nSmartENGINEX AI Assistant\n\n\n\n( {{{{NAMA_ENGINEER}}}} )"
sig_table.rows[0].cells[1].text = f"Disetujui oleh,\nPrincipal Engineer\n\n\n\n( .......................... )"
sig_table.rows[0].cells[1].paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT

# 6. SIMPAN FILE
output_filename = 'template_laporan.docx'
doc.save(output_filename)
print(f"✅ Berhasil! File '{output_filename}' telah dibuat.")